-  id: moretiles-b4-pre
   name: Lock for b4 is not present?
   entry: "b4-test"
   language: system
   stages: [pre-commit]

-  id: moretiles-b4-post
   name: Recreate lock for b4
   entry: "b4-post"
   language: system
   # always_run must be true for all post-commit stage commits
   always_run: true
   stages: [post-commit]
