-  id: moretiles-b4-pre
   name: Lock for b4 exists
   entry: "test"
   language: system
   stages: [pre-commit]
   args:
     - '!'
     - '-e'
     - './.b4.lock'

-  id: moretiles-b4-post
   name: Recreate lock for b4
   entry: "touch"
   language: system
   stages: [post-commit]
   args:
     - './.b4.lock'
